# Generated by Django 5.1.7 on 2025-03-30 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('chapter_id', models.AutoField(db_comment='章节ID', primary_key=True, serialize=False)),
                ('chapter_name', models.CharField(db_comment='章节名称', max_length=100)),
                ('summary', models.TextField(blank=True, db_comment='个人总结', null=True)),
                ('level', models.PositiveIntegerField(blank=True, db_comment='章节等级（1-5）', null=True)),
            ],
            options={
                'db_table': 'chapters',
                'db_table_comment': '章节表',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KnowledgePoints',
            fields=[
                ('point_id', models.AutoField(db_comment='知识点ID', primary_key=True, serialize=False)),
                ('point_name', models.CharField(db_comment='知识点名称', max_length=100)),
                ('content', models.TextField(db_comment='知识点内容')),
                ('personal_understanding', models.TextField(blank=True, db_comment='个人理解', null=True)),
                ('study_count', models.IntegerField(blank=True, db_comment='学习次数', null=True)),
            ],
            options={
                'db_table': 'knowledge_points',
                'db_table_comment': '知识点表',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudyNotes',
            fields=[
                ('note_id', models.AutoField(db_comment='学习笔记ID', primary_key=True, serialize=False)),
                ('note_name', models.CharField(db_comment='学习笔记名称', max_length=100)),
                ('created_at', models.DateTimeField(blank=True, db_comment='创建时间', null=True)),
                ('icon_path', models.CharField(blank=True, db_comment='图标存储路径', max_length=255, null=True)),
            ],
            options={
                'db_table': 'study_notes',
                'db_table_comment': '学习笔记表',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.AutoField(db_comment='问题ID', primary_key=True, serialize=False)),
                ('question_text', models.TextField(db_comment='问题内容')),
                ('question_type', models.CharField(db_comment='问题类型', max_length=2)),
                ('options', models.JSONField(blank=True, db_comment='选项及答案（JSON格式）', null=True)),
                ('analysis', models.TextField(blank=True, db_comment='解析', null=True)),
                ('wrong_count', models.IntegerField(blank=True, db_comment='错误次数', null=True)),
                ('correct_count', models.IntegerField(blank=True, db_comment='正确次数', null=True)),
                ('personal_note', models.TextField(blank=True, db_comment='个人笔记', null=True)),
            ],
            options={
                'db_table': 'questions',
                'db_table_comment': '问题表',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(db_comment='用户ID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_comment='用户名', max_length=50)),
                ('account', models.CharField(db_comment='账号（唯一）', max_length=50, unique=True)),
                ('password_hash', models.CharField(db_comment='密码哈希值（SHA-256）', max_length=64)),
            ],
            options={
                'db_table': 'users',
                'db_table_comment': '用户表',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChapterKnowledgeRelations',
            fields=[
                ('chapter', models.OneToOneField(db_comment='章节ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Learning.chapters')),
            ],
            options={
                'db_table': 'chapter_knowledge_relations',
                'db_table_comment': '章节-知识点关系表',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChapterQuestionRelations',
            fields=[
                ('chapter', models.OneToOneField(db_comment='章节ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Learning.chapters')),
            ],
            options={
                'db_table': 'chapter_question_relations',
                'db_table_comment': '章节-问题关系表',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NoteChapterRelations',
            fields=[
                ('note', models.OneToOneField(db_comment='学习笔记ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Learning.studynotes')),
            ],
            options={
                'db_table': 'note_chapter_relations',
                'db_table_comment': '笔记-章节包含关系表',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionKnowledgeRelations',
            fields=[
                ('question', models.OneToOneField(db_comment='问题ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Learning.questions')),
            ],
            options={
                'db_table': 'question_knowledge_relations',
                'db_table_comment': '问题-知识点关系表',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserNoteRelations',
            fields=[
                ('user', models.OneToOneField(db_comment='用户ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Learning.users')),
            ],
            options={
                'db_table': 'user_note_relations',
                'db_table_comment': '用户-笔记创建关系表',
                'managed': False,
            },
        ),
    ]
